use super::parser::Colors;

type ReloadCmd = Option<(String, Vec<String>, String)>;

pub fn generate_config_content(
    target: &str,
    colors: &Colors,
    home: &str,
) -> Result<(String, String, ReloadCmd), Box<dyn std::error::Error>> {
    match target {
        "kitty" => Ok(generate_kitty_config(colors, home)),
        "waybar" => Ok(generate_waybar_config(colors, home)),
        "hyprland" => Ok(generate_hyprland_config(colors, home)),
        "rofi" => Ok(generate_rofi_config(colors, home)),
        "dunst" => Ok(generate_dunst_config(colors, home)),
        "foot" => Ok(generate_foot_config(colors, home)),
        "neovim" => Ok(generate_neovim_config(colors, home)),
        "gtk" => Ok(generate_gtk_config(colors, home)),
        _ => Err(format!("Unknown target: {}", target).into()),
    }
}

fn generate_kitty_config(colors: &Colors, home: &str) -> (String, String, ReloadCmd) {
    let path = format!("{}/.config/kitty/colors.conf", home);
    let content = format!(
        "# Kitty color config - Generated by themey
foreground {foreground}
background {background}
cursor {cursor}

# Normal colors
color0 {black}
color1 {red}
color2 {green}
color3 {yellow}
color4 {blue}
color5 {magenta}
color6 {cyan}
color7 {white}

# Bright colors
color8 {bright_black}
color9 {bright_red}
color10 {bright_green}
color11 {bright_yellow}
color12 {bright_blue}
color13 {bright_magenta}
color14 {bright_cyan}
color15 {bright_white}
",
        foreground = colors.special.foreground,
        background = colors.special.background,
        cursor = colors.special.cursor,
        black = colors.normal.black,
        red = colors.normal.red,
        green = colors.normal.green,
        yellow = colors.normal.yellow,
        blue = colors.normal.blue,
        magenta = colors.normal.magenta,
        cyan = colors.normal.cyan,
        white = colors.normal.white,
        bright_black = colors.bright.black,
        bright_red = colors.bright.red,
        bright_green = colors.bright.green,
        bright_yellow = colors.bright.yellow,
        bright_blue = colors.bright.blue,
        bright_magenta = colors.bright.magenta,
        bright_cyan = colors.bright.cyan,
        bright_white = colors.bright.white,
    );

    let reload = Some((
        "killall".to_string(),
        vec!["-SIGUSR1".to_string(), "kitty".to_string()],
        "kitty".to_string(),
    ));

    (path, content, reload)
}

fn generate_waybar_config(colors: &Colors, home: &str) -> (String, String, ReloadCmd) {
    let path = format!("{}/.config/waybar/themey-colors.css", home);
    let content = format!(
        "/* Waybar colors - Generated by themey */
/* Import this in your main style.css with: @import \"themey-colors.css\"; */

@define-color themey_background {background};
@define-color themey_foreground {foreground};
@define-color themey_cursor {cursor};

@define-color themey_black {black};
@define-color themey_red {red};
@define-color themey_green {green};
@define-color themey_yellow {yellow};
@define-color themey_blue {blue};
@define-color themey_magenta {magenta};
@define-color themey_cyan {cyan};
@define-color themey_white {white};

@define-color themey_bright_black {bright_black};
@define-color themey_bright_red {bright_red};
@define-color themey_bright_green {bright_green};
@define-color themey_bright_yellow {bright_yellow};
@define-color themey_bright_blue {bright_blue};
@define-color themey_bright_magenta {bright_magenta};
@define-color themey_bright_cyan {bright_cyan};
@define-color themey_bright_white {bright_white};
",
        background = colors.special.background,
        foreground = colors.special.foreground,
        cursor = colors.special.cursor,
        black = colors.normal.black,
        red = colors.normal.red,
        green = colors.normal.green,
        yellow = colors.normal.yellow,
        blue = colors.normal.blue,
        magenta = colors.normal.magenta,
        cyan = colors.normal.cyan,
        white = colors.normal.white,
        bright_black = colors.bright.black,
        bright_red = colors.bright.red,
        bright_green = colors.bright.green,
        bright_yellow = colors.bright.yellow,
        bright_blue = colors.bright.blue,
        bright_magenta = colors.bright.magenta,
        bright_cyan = colors.bright.cyan,
        bright_white = colors.bright.white,
    );

    let reload = Some((
        "sh".to_string(),
        vec![
            "-c".to_string(),
            "pkill -x waybar; waybar >/dev/null 2>&1 & disown".to_string()
        ],
        "waybar".to_string(),
    ));

    (path, content, reload)
}

fn generate_hyprland_config(colors: &Colors, home: &str) -> (String, String, ReloadCmd) {
    let path = format!("{}/.config/hypr/colors.conf", home);
    let content = format!(
        "# Hyprland colors - Generated by themey
$background = rgb({background})
$foreground = rgb({foreground})
$cursor = rgb({cursor})

$black = rgb({black})
$red = rgb({red})
$green = rgb({green})
$yellow = rgb({yellow})
$blue = rgb({blue})
$magenta = rgb({magenta})
$cyan = rgb({cyan})
$white = rgb({white})

$bright_black = rgb({bright_black})
$bright_red = rgb({bright_red})
$bright_green = rgb({bright_green})
$bright_yellow = rgb({bright_yellow})
$bright_blue = rgb({bright_blue})
$bright_magenta = rgb({bright_magenta})
$bright_cyan = rgb({bright_cyan})
$bright_white = rgb({bright_white})

# Border colors
general {{
    col.active_border = $cyan $blue 45deg
    col.inactive_border = $black
}}
",
        background = hex_to_rgb(&colors.special.background),
        foreground = hex_to_rgb(&colors.special.foreground),
        cursor = hex_to_rgb(&colors.special.cursor),
        black = hex_to_rgb(&colors.normal.black),
        red = hex_to_rgb(&colors.normal.red),
        green = hex_to_rgb(&colors.normal.green),
        yellow = hex_to_rgb(&colors.normal.yellow),
        blue = hex_to_rgb(&colors.normal.blue),
        magenta = hex_to_rgb(&colors.normal.magenta),
        cyan = hex_to_rgb(&colors.normal.cyan),
        white = hex_to_rgb(&colors.normal.white),
        bright_black = hex_to_rgb(&colors.bright.black),
        bright_red = hex_to_rgb(&colors.bright.red),
        bright_green = hex_to_rgb(&colors.bright.green),
        bright_yellow = hex_to_rgb(&colors.bright.yellow),
        bright_blue = hex_to_rgb(&colors.bright.blue),
        bright_magenta = hex_to_rgb(&colors.bright.magenta),
        bright_cyan = hex_to_rgb(&colors.bright.cyan),
        bright_white = hex_to_rgb(&colors.bright.white),
    );

    let reload = Some((
        "hyprctl".to_string(),
        vec!["reload".to_string()],
        "hyprland".to_string(),
    ));

    (path, content, reload)
}

fn generate_rofi_config(colors: &Colors, home: &str) -> (String, String, ReloadCmd) {
    let path = format!("{}/.config/rofi/colors.rasi", home);
    let content = format!(
        "/* Rofi colors - Generated by themey */
* {{
    background: {background};
    background-alt: {bright_black};
    foreground: {foreground};
    border: {blue};
    cursor: {cursor};

    black: {black};
    red: {red};
    green: {green};
    yellow: {yellow};
    blue: {blue};
    magenta: {magenta};
    cyan: {cyan};
    white: {white};

    bright-black: {bright_black};
    bright-red: {bright_red};
    bright-green: {bright_green};
    bright-yellow: {bright_yellow};
    bright-blue: {bright_blue};
    bright-magenta: {bright_magenta};
    bright-cyan: {bright_cyan};
    bright-white: {bright_white};

    background-color: @background;
    text-color: @foreground;
    selected-normal-background: @blue;
    selected-normal-foreground: @background;
}}
",
        background = colors.special.background,
        foreground = colors.special.foreground,
        cursor = colors.special.cursor,
        black = colors.normal.black,
        red = colors.normal.red,
        green = colors.normal.green,
        yellow = colors.normal.yellow,
        blue = colors.normal.blue,
        magenta = colors.normal.magenta,
        cyan = colors.normal.cyan,
        white = colors.normal.white,
        bright_black = colors.bright.black,
        bright_red = colors.bright.red,
        bright_green = colors.bright.green,
        bright_yellow = colors.bright.yellow,
        bright_blue = colors.bright.blue,
        bright_magenta = colors.bright.magenta,
        bright_cyan = colors.bright.cyan,
        bright_white = colors.bright.white,
    );

    (path, content, None)
}

fn generate_dunst_config(colors: &Colors, home: &str) -> (String, String, ReloadCmd) {
    let path = format!("{}/.config/dunst/dunstrc.d/colors.conf", home);
    let content = format!(
        "# Dunst colors - Generated by themey
[urgency_low]
background = \"{background}\"
foreground = \"{foreground}\"
frame_color = \"{blue}\"

[urgency_normal]
background = \"{background}\"
foreground = \"{foreground}\"
frame_color = \"{cyan}\"

[urgency_critical]
background = \"{background}\"
foreground = \"{foreground}\"
frame_color = \"{red}\"
",
        background = colors.special.background,
        foreground = colors.special.foreground,
        blue = colors.normal.blue,
        cyan = colors.normal.cyan,
        red = colors.normal.red,
    );

    (path, content, None)
}

fn generate_foot_config(colors: &Colors, home: &str) -> (String, String, ReloadCmd) {
    let path = format!("{}/.config/foot/colors.ini", home);
    let content = format!(
        "# Foot colors - Generated by themey
[colors]
foreground={foreground}
background={background}
cursor={background} {cursor}

## Normal/regular colors (color palette 0-7)
regular0={black}
regular1={red}
regular2={green}
regular3={yellow}
regular4={blue}
regular5={magenta}
regular6={cyan}
regular7={white}

## Bright colors (color palette 8-15)
bright0={bright_black}
bright1={bright_red}
bright2={bright_green}
bright3={bright_yellow}
bright4={bright_blue}
bright5={bright_magenta}
bright6={bright_cyan}
bright7={bright_white}
",
        foreground = strip_hash(&colors.special.foreground),
        background = strip_hash(&colors.special.background),
        cursor = strip_hash(&colors.special.cursor),
        black = strip_hash(&colors.normal.black),
        red = strip_hash(&colors.normal.red),
        green = strip_hash(&colors.normal.green),
        yellow = strip_hash(&colors.normal.yellow),
        blue = strip_hash(&colors.normal.blue),
        magenta = strip_hash(&colors.normal.magenta),
        cyan = strip_hash(&colors.normal.cyan),
        white = strip_hash(&colors.normal.white),
        bright_black = strip_hash(&colors.bright.black),
        bright_red = strip_hash(&colors.bright.red),
        bright_green = strip_hash(&colors.bright.green),
        bright_yellow = strip_hash(&colors.bright.yellow),
        bright_blue = strip_hash(&colors.bright.blue),
        bright_magenta = strip_hash(&colors.bright.magenta),
        bright_cyan = strip_hash(&colors.bright.cyan),
        bright_white = strip_hash(&colors.bright.white),
    );

    // Foot doesn't support hot-reloading, user needs to restart instances
    (path, content, None)
}

fn hex_to_rgb(hex: &str) -> String {
    let hex = hex.trim_start_matches('#');
    format!("{}", hex)
}

fn strip_hash(hex: &str) -> String {
    hex.trim_start_matches('#').to_string()
}

fn generate_gtk_config(colors: &Colors, home: &str) -> (String, String, ReloadCmd) {
    // Create theme in ~/.themes/Themey/
    let theme_name = "Themey";
    let base_path = format!("{}/.themes/{}", home, theme_name);

    // We'll return the gtk-3.0 path as the main path
    // But we need to create both GTK3 and GTK4 directories
    let gtk3_dir = format!("{}/gtk-3.0", base_path);
    let gtk4_dir = format!("{}/gtk-4.0", base_path);

    // Create directories
    std::fs::create_dir_all(&gtk3_dir).ok();
    std::fs::create_dir_all(&gtk4_dir).ok();

    // Also create index.theme file for the theme to be recognized
    let index_content = format!(
        "[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Themey
Comment=Theme generated by Themey
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Themey
MetacityTheme=Themey
IconTheme=Adwaita
CursorTheme=Adwaita
"
    );
    std::fs::write(format!("{}/index.theme", base_path), index_content).ok();

    let gtk_css = format!(
        "/* GTK theme - Generated by themey */

/* Color definitions */
@define-color theme_fg_color {foreground};
@define-color theme_bg_color {background};
@define-color theme_base_color {background};
@define-color theme_text_color {foreground};
@define-color theme_selected_bg_color {blue};
@define-color theme_selected_fg_color {background};
@define-color insensitive_bg_color mix({background}, {foreground}, 0.9);
@define-color insensitive_fg_color mix({foreground}, {background}, 0.5);
@define-color insensitive_base_color {background};
@define-color theme_unfocused_fg_color mix({foreground}, {background}, 0.7);
@define-color theme_unfocused_bg_color {background};
@define-color theme_unfocused_base_color {background};
@define-color theme_unfocused_text_color mix({foreground}, {background}, 0.7);
@define-color theme_unfocused_selected_bg_color mix({blue}, {background}, 0.7);
@define-color theme_unfocused_selected_fg_color {background};
@define-color borders mix({foreground}, {background}, 0.15);
@define-color unfocused_borders mix({foreground}, {background}, 0.1);

@define-color warning_color {yellow};
@define-color error_color {red};
@define-color success_color {green};

/* Additional semantic colors */
@define-color accent_bg_color {blue};
@define-color accent_fg_color {background};
@define-color accent_color {blue};
@define-color destructive_bg_color {red};
@define-color destructive_fg_color {background};
@define-color destructive_color {red};
@define-color headerbar_bg_color {background};
@define-color headerbar_fg_color {foreground};
@define-color headerbar_border_color mix({foreground}, {background}, 0.15);
@define-color headerbar_backdrop_color {background};
@define-color headerbar_shade_color rgba(0, 0, 0, 0.36);
@define-color card_bg_color mix({background}, {foreground}, 0.05);
@define-color card_fg_color {foreground};
@define-color card_shade_color rgba(0, 0, 0, 0.36);
@define-color dialog_bg_color {background};
@define-color dialog_fg_color {foreground};
@define-color popover_bg_color {background};
@define-color popover_fg_color {foreground};
@define-color shade_color rgba(0, 0, 0, 0.36);
@define-color scrollbar_outline_color rgba(0, 0, 0, 0.5);
@define-color window_bg_color {background};
@define-color window_fg_color {foreground};
@define-color view_bg_color {background};
@define-color view_fg_color {foreground};

/* Apply base colors */
* {{
    background-color: @theme_bg_color;
    color: @theme_fg_color;
}}

/* Buttons */
button {{
    background-color: mix(@theme_bg_color, @theme_fg_color, 0.1);
    color: @theme_fg_color;
    border: 1px solid @borders;
}}

button:hover {{
    background-color: mix(@theme_bg_color, @theme_fg_color, 0.15);
}}

button:active {{
    background-color: @theme_selected_bg_color;
}}

/* Entries */
entry {{
    background-color: @theme_base_color;
    color: @theme_text_color;
    border: 1px solid @borders;
}}

entry:focus {{
    border-color: @theme_selected_bg_color;
}}

/* Selection */
selection {{
    background-color: @theme_selected_bg_color;
    color: @theme_selected_fg_color;
}}

/* Scrollbars */
scrollbar {{
    background-color: @theme_bg_color;
}}

scrollbar slider {{
    background-color: mix(@theme_fg_color, @theme_bg_color, 0.3);
}}

scrollbar slider:hover {{
    background-color: mix(@theme_fg_color, @theme_bg_color, 0.4);
}}

/* Headerbar */
headerbar {{
    background-color: @headerbar_bg_color;
    color: @headerbar_fg_color;
    border-bottom: 1px solid @headerbar_border_color;
}}

/* Menus */
menu,
.menu {{
    background-color: @popover_bg_color;
    color: @popover_fg_color;
}}

menuitem:hover {{
    background-color: @theme_selected_bg_color;
    color: @theme_selected_fg_color;
}}

/* Tooltips */
tooltip {{
    background-color: mix(@theme_bg_color, @theme_fg_color, 0.2);
    color: @theme_fg_color;
}}

/* Notebook tabs */
notebook > header > tabs > tab {{
    background-color: mix(@theme_bg_color, @theme_fg_color, 0.05);
    color: @theme_fg_color;
}}

notebook > header > tabs > tab:checked {{
    background-color: @theme_bg_color;
    color: @theme_selected_bg_color;
}}
",
        foreground = colors.special.foreground,
        background = colors.special.background,
        blue = colors.normal.blue,
        red = colors.normal.red,
        green = colors.normal.green,
        yellow = colors.normal.yellow,
    );

    // Write GTK3 file
    let gtk3_path = format!("{}/gtk.css", gtk3_dir);
    std::fs::write(&gtk3_path, &gtk_css).ok();

    // Write GTK4 file
    let gtk4_path = format!("{}/gtk.css", gtk4_dir);
    std::fs::write(&gtk4_path, &gtk_css).ok();

    // Apply the theme using gsettings
    let reload = Some((
        "sh".to_string(),
        vec![
            "-c".to_string(),
            format!(
                "gsettings set org.gnome.desktop.interface gtk-theme '{}' && \
                 gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'",
                theme_name
            )
        ],
        "GTK".to_string(),
    ));

    (gtk3_path, gtk_css, reload)
}

// Add this function to src/plugins/templates.rs

fn generate_neovim_config(colors: &Colors, home: &str) -> (String, String, ReloadCmd) {
    let path = format!("{}/.config/nvim/colors/themey.lua", home);
    let content = format!(
        "-- Neovim colorscheme - Generated by themey
-- This file is auto-generated. Do not edit manually.

vim.cmd('hi clear')
if vim.fn.exists('syntax_on') then
  vim.cmd('syntax reset')
end

vim.o.termguicolors = true
vim.g.colors_name = 'themey'

-- Define color palette
local colors = {{
  background = '{background}',
  foreground = '{foreground}',
  cursor = '{cursor}',

  black = '{black}',
  red = '{red}',
  green = '{green}',
  yellow = '{yellow}',
  blue = '{blue}',
  magenta = '{magenta}',
  cyan = '{cyan}',
  white = '{white}',

  bright_black = '{bright_black}',
  bright_red = '{bright_red}',
  bright_green = '{bright_green}',
  bright_yellow = '{bright_yellow}',
  bright_blue = '{bright_blue}',
  bright_magenta = '{bright_magenta}',
  bright_cyan = '{bright_cyan}',
  bright_white = '{bright_white}',
}}

-- Helper function to set highlights
local function hi(group, opts)
  local cmd = 'highlight ' .. group
  if opts.fg then cmd = cmd .. ' guifg=' .. opts.fg end
  if opts.bg then cmd = cmd .. ' guibg=' .. opts.bg end
  if opts.style then cmd = cmd .. ' gui=' .. opts.style end
  if opts.sp then cmd = cmd .. ' guisp=' .. opts.sp end
  vim.cmd(cmd)
end

-- Editor highlights
hi('Normal', {{ fg = colors.foreground, bg = colors.background }})
hi('NormalFloat', {{ fg = colors.foreground, bg = colors.black }})
hi('FloatBorder', {{ fg = colors.bright_black, bg = colors.black }})
hi('Cursor', {{ fg = colors.background, bg = colors.cursor }})
hi('CursorLine', {{ bg = colors.black }})
hi('CursorColumn', {{ bg = colors.black }})
hi('LineNr', {{ fg = colors.bright_black }})
hi('CursorLineNr', {{ fg = colors.yellow, style = 'bold' }})
hi('SignColumn', {{ bg = colors.background }})
hi('ColorColumn', {{ bg = colors.black }})
hi('VertSplit', {{ fg = colors.bright_black }})
hi('Visual', {{ bg = colors.bright_black }})
hi('VisualNOS', {{ bg = colors.bright_black }})
hi('Search', {{ fg = colors.background, bg = colors.yellow }})
hi('IncSearch', {{ fg = colors.background, bg = colors.bright_yellow }})
hi('MatchParen', {{ fg = colors.bright_cyan, style = 'bold' }})
hi('Folded', {{ fg = colors.bright_black, bg = colors.black }})
hi('FoldColumn', {{ fg = colors.bright_black, bg = colors.background }})

-- Statusline
hi('StatusLine', {{ fg = colors.foreground, bg = colors.black }})
hi('StatusLineNC', {{ fg = colors.bright_black, bg = colors.black }})
hi('WildMenu', {{ fg = colors.background, bg = colors.blue }})

-- Tabs
hi('TabLine', {{ fg = colors.bright_black, bg = colors.black }})
hi('TabLineFill', {{ bg = colors.black }})
hi('TabLineSel', {{ fg = colors.foreground, bg = colors.background, style = 'bold' }})

-- Popups and menus
hi('Pmenu', {{ fg = colors.foreground, bg = colors.black }})
hi('PmenuSel', {{ fg = colors.background, bg = colors.blue }})
hi('PmenuSbar', {{ bg = colors.bright_black }})
hi('PmenuThumb', {{ bg = colors.white }})

-- Syntax highlighting
hi('Comment', {{ fg = colors.bright_black, style = 'italic' }})
hi('Constant', {{ fg = colors.magenta }})
hi('String', {{ fg = colors.green }})
hi('Character', {{ fg = colors.green }})
hi('Number', {{ fg = colors.magenta }})
hi('Boolean', {{ fg = colors.magenta }})
hi('Float', {{ fg = colors.magenta }})

hi('Identifier', {{ fg = colors.cyan }})
hi('Function', {{ fg = colors.blue }})

hi('Statement', {{ fg = colors.red }})
hi('Conditional', {{ fg = colors.red }})
hi('Repeat', {{ fg = colors.red }})
hi('Label', {{ fg = colors.red }})
hi('Operator', {{ fg = colors.foreground }})
hi('Keyword', {{ fg = colors.red }})
hi('Exception', {{ fg = colors.red }})

hi('PreProc', {{ fg = colors.yellow }})
hi('Include', {{ fg = colors.blue }})
hi('Define', {{ fg = colors.yellow }})
hi('Macro', {{ fg = colors.yellow }})
hi('PreCondit', {{ fg = colors.yellow }})

hi('Type', {{ fg = colors.yellow }})
hi('StorageClass', {{ fg = colors.yellow }})
hi('Structure', {{ fg = colors.yellow }})
hi('Typedef', {{ fg = colors.yellow }})

hi('Special', {{ fg = colors.cyan }})
hi('SpecialChar', {{ fg = colors.cyan }})
hi('Tag', {{ fg = colors.cyan }})
hi('Delimiter', {{ fg = colors.foreground }})
hi('SpecialComment', {{ fg = colors.bright_black, style = 'italic' }})
hi('Debug', {{ fg = colors.red }})

hi('Underlined', {{ fg = colors.blue, style = 'underline' }})
hi('Ignore', {{ fg = colors.bright_black }})
hi('Error', {{ fg = colors.bright_red, bg = colors.background }})
hi('Todo', {{ fg = colors.yellow, bg = colors.background, style = 'bold' }})

-- Diff
hi('DiffAdd', {{ fg = colors.green, bg = colors.black }})
hi('DiffChange', {{ fg = colors.yellow, bg = colors.black }})
hi('DiffDelete', {{ fg = colors.red, bg = colors.black }})
hi('DiffText', {{ fg = colors.blue, bg = colors.black, style = 'bold' }})

-- Git signs
hi('GitSignsAdd', {{ fg = colors.green }})
hi('GitSignsChange', {{ fg = colors.yellow }})
hi('GitSignsDelete', {{ fg = colors.red }})

-- Treesitter highlights
hi('TSAnnotation', {{ fg = colors.yellow }})
hi('TSAttribute', {{ fg = colors.cyan }})
hi('TSBoolean', {{ fg = colors.magenta }})
hi('TSCharacter', {{ fg = colors.green }})
hi('TSComment', {{ fg = colors.bright_black, style = 'italic' }})
hi('TSConditional', {{ fg = colors.red }})
hi('TSConstant', {{ fg = colors.magenta }})
hi('TSConstBuiltin', {{ fg = colors.magenta }})
hi('TSConstMacro', {{ fg = colors.magenta }})
hi('TSConstructor', {{ fg = colors.blue }})
hi('TSError', {{ fg = colors.bright_red }})
hi('TSException', {{ fg = colors.red }})
hi('TSField', {{ fg = colors.cyan }})
hi('TSFloat', {{ fg = colors.magenta }})
hi('TSFunction', {{ fg = colors.blue }})
hi('TSFuncBuiltin', {{ fg = colors.blue }})
hi('TSFuncMacro', {{ fg = colors.blue }})
hi('TSInclude', {{ fg = colors.blue }})
hi('TSKeyword', {{ fg = colors.red }})
hi('TSKeywordFunction', {{ fg = colors.red }})
hi('TSKeywordOperator', {{ fg = colors.red }})
hi('TSLabel', {{ fg = colors.red }})
hi('TSMethod', {{ fg = colors.blue }})
hi('TSNamespace', {{ fg = colors.yellow }})
hi('TSNumber', {{ fg = colors.magenta }})
hi('TSOperator', {{ fg = colors.foreground }})
hi('TSParameter', {{ fg = colors.cyan }})
hi('TSParameterReference', {{ fg = colors.cyan }})
hi('TSProperty', {{ fg = colors.cyan }})
hi('TSPunctDelimiter', {{ fg = colors.foreground }})
hi('TSPunctBracket', {{ fg = colors.foreground }})
hi('TSPunctSpecial', {{ fg = colors.cyan }})
hi('TSRepeat', {{ fg = colors.red }})
hi('TSString', {{ fg = colors.green }})
hi('TSStringRegex', {{ fg = colors.green }})
hi('TSStringEscape', {{ fg = colors.cyan }})
hi('TSSymbol', {{ fg = colors.cyan }})
hi('TSTag', {{ fg = colors.red }})
hi('TSTagDelimiter', {{ fg = colors.foreground }})
hi('TSText', {{ fg = colors.foreground }})
hi('TSStrong', {{ style = 'bold' }})
hi('TSEmphasis', {{ style = 'italic' }})
hi('TSUnderline', {{ style = 'underline' }})
hi('TSStrike', {{ style = 'strikethrough' }})
hi('TSTitle', {{ fg = colors.blue, style = 'bold' }})
hi('TSLiteral', {{ fg = colors.green }})
hi('TSURI', {{ fg = colors.blue, style = 'underline' }})
hi('TSType', {{ fg = colors.yellow }})
hi('TSTypeBuiltin', {{ fg = colors.yellow }})
hi('TSVariable', {{ fg = colors.foreground }})
hi('TSVariableBuiltin', {{ fg = colors.cyan }})

-- LSP highlights
hi('DiagnosticError', {{ fg = colors.red }})
hi('DiagnosticWarn', {{ fg = colors.yellow }})
hi('DiagnosticInfo', {{ fg = colors.blue }})
hi('DiagnosticHint', {{ fg = colors.cyan }})
hi('DiagnosticUnderlineError', {{ sp = colors.red, style = 'underline' }})
hi('DiagnosticUnderlineWarn', {{ sp = colors.yellow, style = 'underline' }})
hi('DiagnosticUnderlineInfo', {{ sp = colors.blue, style = 'underline' }})
hi('DiagnosticUnderlineHint', {{ sp = colors.cyan, style = 'underline' }})

-- Terminal colors
vim.g.terminal_color_0 = colors.black
vim.g.terminal_color_1 = colors.red
vim.g.terminal_color_2 = colors.green
vim.g.terminal_color_3 = colors.yellow
vim.g.terminal_color_4 = colors.blue
vim.g.terminal_color_5 = colors.magenta
vim.g.terminal_color_6 = colors.cyan
vim.g.terminal_color_7 = colors.white
vim.g.terminal_color_8 = colors.bright_black
vim.g.terminal_color_9 = colors.bright_red
vim.g.terminal_color_10 = colors.bright_green
vim.g.terminal_color_11 = colors.bright_yellow
vim.g.terminal_color_12 = colors.bright_blue
vim.g.terminal_color_13 = colors.bright_magenta
vim.g.terminal_color_14 = colors.bright_cyan
vim.g.terminal_color_15 = colors.bright_white
",
        background = colors.special.background,
        foreground = colors.special.foreground,
        cursor = colors.special.cursor,
        black = colors.normal.black,
        red = colors.normal.red,
        green = colors.normal.green,
        yellow = colors.normal.yellow,
        blue = colors.normal.blue,
        magenta = colors.normal.magenta,
        cyan = colors.normal.cyan,
        white = colors.normal.white,
        bright_black = colors.bright.black,
        bright_red = colors.bright.red,
        bright_green = colors.bright.green,
        bright_yellow = colors.bright.yellow,
        bright_blue = colors.bright.blue,
        bright_magenta = colors.bright.magenta,
        bright_cyan = colors.bright.cyan,
        bright_white = colors.bright.white,
    );

    // Note: We don't auto-reload Neovim as it requires running :colorscheme themey
    // Users can add an autocmd in their config if they want auto-reloading
    (path, content, None)
}